### ISSUE TITLE
No compression

### ISSUE THREAD

**Issue by oldmud0** [mnaamani/enet-npm#2]
There is absolutely no support for compression in the bindings. More specifically, I'm wondering if [`int enet_host_compress_with_range_coder (ENetHost* host)`](http://enet.bespin.org/group__host.html#ga444b74e7b70d97e2abd02328419be3f4) has been implemented.

**Comment by mnaamani** [comment]
Sorry it took a while, I added the enableCompression and disableCompression methods to the host in
49ba5d2e32c6cb23a29d34bc09b6a4eb53a76463

There are also a few API changes and some bug fixes.

**Comment by oldmud0** [comment]
Finally! :sunglasses:
